### ISSUE TITLE
Optimise mini browsing and searching

### ISSUE THREAD

**Issue by anaximander23** [aluhrs13/TheMiniIndex#116]
Parts of the logic for searching and filtering minis are inefficient, making checks inside of loops that could be outside, repeating code that could be combined, etc. Refactoring this code could improve performance as well as maintainability.

**Comment by aluhrs13** [comment]
As you're looking at this, we'll probably be able to close out #61, #78, and get a start on #105.

**Comment by aluhrs13** [comment]
Done!
