### ISSUE TITLE
Send out first newsletter

### ISSUE THREAD

**Issue by aluhrs13** [aluhrs13/TheMiniIndex#123]
I want to start engaging in email a bit more, so I'm pulling together an email with major updates

- [x] Wait until #115 has been merged for a bit
- [x] Nail down redesign color scheme (open to opinions here, not in love with the blue below, I like the green I think)
- [x] #27 and #112 
- [x] Export email list and import into SendGrid
- [x] Verify it's working with a small group
- [x] Send!

Screenshot of current draft:
![image](https://user-images.githubusercontent.com/3189095/72405522-1cc58d00-370e-11ea-84bd-615a3a6348f7.png)

**Comment by anaximander23** [comment]
You may have spotted it since this screenshot, but there's a rogue "are" in the very last sentence of the newsletter.
