### ISSUE TITLE
Adding a Mini is making extra Creators and SourceSites

### ISSUE THREAD

**Issue by aluhrs13** [aluhrs13/TheMiniIndex#134]
This is a bit weird, did a bit of debugging but couldn't track it down, so writing down info.

For every new Mini, a new Creator is being made, a new Sourcesite is being made, but the MiniSourceSite is correctly point to the "first" of that Creator. So every new Mini is creating a "dangling" Creator and Sourcesite with 0 minis. For example:

- https://theminiindex.com/Creators/Details?id=1402
- https://theminiindex.com/Creators/Details?id=1422
- https://theminiindex.com/Creators/Details?id=1423

All three Minis of the first creator are being associated with that creator, but the latter two made a new creator (1422 and 1423) in the process. This isn't a huge problem since writing a SQL script to clean this up isn't bad, but it's something we should look at sooner rather than later.

**Comment by anaximander23** [comment]
I think I know what might be causing this. I'll take a look.
