### ISSUE TITLE
Idea - "Tinder" style tagging workflow/view

### ISSUE THREAD

**Issue by aluhrs13** [aluhrs13/TheMiniIndex#140]
Key goals is to enable a new style of random browsing (which a lot of people are doing), grow investment into the site (https://www.nirandfar.com/makeyourusersdothework/), and improve tagging.
- [x] Show user an untagged Mini 
- [x] Show suggested tags
- [x] Let them choose to add some, or easily jump to a random new Mini
- [x] Show a "how to tag" banner with some basic suggestions and link out. If they aren't logged in, use that space to nicely ask them to make an account.

**Comment by anaximander23** [comment]
I had something similar in mind, based on the StackOverflow review queues. It could be included under the "Help improve TMI" dropdown, possibly with a badge indicating how many minis need attention, or providing a more urgent call to action when the count gets large.

![image](https://user-images.githubusercontent.com/7376990/75367443-3daa0200-58b8-11ea-8da0-72450c3b836d.png)

![image](https://user-images.githubusercontent.com/7376990/75367594-777b0880-58b8-11ea-803b-9417dec07fa3.png)

notes:
1. Explain why this thing is being shown to them (not enough tags, possibly contradictory tags, missing a specific kind of tag, mini is appearing too frequently/infrequently in searches, etc)
2. Offer options for how to proceed (add tags, remove tags, mark as ok) and offer an option to skip and see another if the user doesn't want to deal with this one, or isn't sure how to.

Not shown on that screenshot is the way that SO allows for multiple people to review the same thing, and then uses consensus as a way to screen out bad actions. A similar model could be used, adding or removing tags only if a certain number of users do the same.
