### ISSUE TITLE
Clicking on the star button doesn't seem to do anything

### ISSUE THREAD

**Issue by Hellmark** [aluhrs13/TheMiniIndex#148]
Normally you'd expect clicking the star button would make it available in the starred section, but nothing ever shows up there.

**Comment by aluhrs13** [comment]
@anaximander23 looks like the webpack starred script is hitting an issue with jQuery not being available? Spent a few minutes looking at it, but nothing is jumping out at me.

stars.js:1 Uncaught ReferenceError: $ is not defined
    at Object../wwwroot/js/stars.js (stars.js:1)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83

**Comment by aluhrs13** [comment]
Found the problem. Fix going out shortly. Thanks for reporting this!
