### ISSUE TITLE
Some AtelierStoria minis not parsing

### ISSUE THREAD

**Issue by aluhrs13** [aluhrs13/TheMiniIndex#216]
Example - https://atelierstoria.com/collections/silver-wings/myra

**Comment by Oriol-GG** [comment]
Thanks @aluhrs13, I know the reason. That miniature has several variants (Pose-A, Pose-B, Set-AB).
When a miniature has multiple variants, for the parser to know which one is referring to, the link needs to be on the shape `https://atelierstoria.com/collections/silver-wings/myra?variant=Pose-A`.
Saho (the sculptor) intends to submit all her minis herself, so shouldn't be an issue.

However, considering anyone can submit and the project is open, I want to fix this. I'll make a change in the website and then another PR here to support the case of defaulting to the first variant in a case of a mini with multiple variants without the variant specified in the link. Will probably get to it around the weekend.
