### ISSUE TITLE
Please add prusaprinters.org as a source website.

### ISSUE THREAD

**Issue by TheRooster13** [aluhrs13/TheMiniIndex#218]
Thingiverse is so unreliable lately. I've changed where I upload.

**Comment by anaximander23** [comment]
A quick poke around revealed a GraphQL backend that we could use; `https://www.prusaprinters.org/graphql/` is the URL. Example query below.

![image](https://user-images.githubusercontent.com/7376990/97006967-8f368980-1538-11eb-9dda-62e739233f29.png)

Doesn't seem to require an API key, but I'd consider implementing a rate limit just to be nice.

**Comment by aluhrs13** [comment]
Prusa is next on the list for when I get time, it's a bit harder than most. I'm part-way through hacking together a query that works so I don't have to pull in an entire GraphQL library.

**Comment by aluhrs13** [comment]
@TheRooster13 - PrusaPrinters support is now done! I'll note here and maybe in a couple other places, that duplicate detection across sites doesn't exist, so if there's a mini on multiple sites (most notably a problem for mz4250's models) it'll show up twice if added from both sources for now.
