### ISSUE TITLE
Investigate using Shapeways API for Shapeways additions.

### ISSUE THREAD

**Issue by aluhrs13** [aluhrs13/TheMiniIndex#55]

**Comment by anaximander23** [comment]
Making a start on this as part of my current refactor. Looks straightforward so far.

**Comment by anaximander23** [comment]
Looks like the API gives you access to your *own* models, for ecommerce purposes. I don't see a way to get info on other peoples' models via the API.

**Comment by aluhrs13** [comment]
Closing this out since it appears Shapeways API isn't intended for what we need.
