### ISSUE TITLE
Deploying to production needs to run migrations

### ISSUE THREAD

**Issue by aluhrs13** [aluhrs13/TheMiniIndex#95]
Copy steps from PPE pipeline.

**Comment by anaximander23** [comment]
I *think* this should be as simple as running `dotnet ef database update --project MiniIndex\MiniIndex.csproj` on deployment. I've been running that locally and it works fine.

The caveat is that the DBInit.sql script is written against the current schema, before my changes, so what I've been doing is:

- run  `dotnet ef database update Initial` to deploy database schema as of when I joined the project
- run DBInit.sql
- run  `dotnet ef database update` to run all migrations up to the latest version (which include SQL to migrate data into the new schema as it goes)

In theory, once we reach production only that last step should be needed, obviously.
